-- ============================================================
-- 0003_seed_default_template.sql
-- ANTIGO: criava um template padrão curado para a "org raiz".
-- SUPERSEDIDO: não existe mais org raiz — cada empresa cria o próprio
-- template padrão no fluxo de "Criar empresa" (`organizations/create`).
-- Mantido como no-op para preservar o histórico de migrations.
-- ============================================================