-- ============================================================
-- 0008_auto_create_default_template_per_org.sql
-- ANTIGO: trigger handle_new_user atribuía o usuário à "primeira org"
-- existente e criava template padrão para ela (comportamento errado de
-- tenancy). SUPERSEDIDO pela migration 0011 (org = null até criar
-- empresa) e pelo fluxo de criação de empresa (`organizations/create`).
-- Mantido como no-op para preservar o histórico de migrations.
-- ============================================================